server:
  port: 8081

spring:
  application:
    name: follower-service
  datasource:

    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5332/friend_db
    username: admin
    password: admin
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/root-changelog.xml