/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ru.sadykov.socialnetwork.friend.event;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class FriendAddEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3217891716137869049L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FriendAddEvent\",\"namespace\":\"ru.sadykov.socialnetwork.friend.event\",\"fields\":[{\"name\":\"userId\",\"type\":\"long\"},{\"name\":\"subscriberId\",\"type\":\"long\"},{\"name\":\"message\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FriendAddEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FriendAddEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<FriendAddEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<FriendAddEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<FriendAddEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this FriendAddEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a FriendAddEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a FriendAddEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static FriendAddEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long userId;
  private long subscriberId;
  private java.lang.CharSequence message;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FriendAddEvent() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param subscriberId The new value for subscriberId
   * @param message The new value for message
   */
  public FriendAddEvent(java.lang.Long userId, java.lang.Long subscriberId, java.lang.CharSequence message) {
    this.userId = userId;
    this.subscriberId = subscriberId;
    this.message = message;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return subscriberId;
    case 2: return message;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.Long)value$; break;
    case 1: subscriberId = (java.lang.Long)value$; break;
    case 2: message = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public long getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(long value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'subscriberId' field.
   * @return The value of the 'subscriberId' field.
   */
  public long getSubscriberId() {
    return subscriberId;
  }


  /**
   * Sets the value of the 'subscriberId' field.
   * @param value the value to set.
   */
  public void setSubscriberId(long value) {
    this.subscriberId = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Creates a new FriendAddEvent RecordBuilder.
   * @return A new FriendAddEvent RecordBuilder
   */
  public static ru.sadykov.socialnetwork.friend.event.FriendAddEvent.Builder newBuilder() {
    return new ru.sadykov.socialnetwork.friend.event.FriendAddEvent.Builder();
  }

  /**
   * Creates a new FriendAddEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FriendAddEvent RecordBuilder
   */
  public static ru.sadykov.socialnetwork.friend.event.FriendAddEvent.Builder newBuilder(ru.sadykov.socialnetwork.friend.event.FriendAddEvent.Builder other) {
    if (other == null) {
      return new ru.sadykov.socialnetwork.friend.event.FriendAddEvent.Builder();
    } else {
      return new ru.sadykov.socialnetwork.friend.event.FriendAddEvent.Builder(other);
    }
  }

  /**
   * Creates a new FriendAddEvent RecordBuilder by copying an existing FriendAddEvent instance.
   * @param other The existing instance to copy.
   * @return A new FriendAddEvent RecordBuilder
   */
  public static ru.sadykov.socialnetwork.friend.event.FriendAddEvent.Builder newBuilder(ru.sadykov.socialnetwork.friend.event.FriendAddEvent other) {
    if (other == null) {
      return new ru.sadykov.socialnetwork.friend.event.FriendAddEvent.Builder();
    } else {
      return new ru.sadykov.socialnetwork.friend.event.FriendAddEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for FriendAddEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FriendAddEvent>
    implements org.apache.avro.data.RecordBuilder<FriendAddEvent> {

    private long userId;
    private long subscriberId;
    private java.lang.CharSequence message;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ru.sadykov.socialnetwork.friend.event.FriendAddEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.subscriberId)) {
        this.subscriberId = data().deepCopy(fields()[1].schema(), other.subscriberId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.message)) {
        this.message = data().deepCopy(fields()[2].schema(), other.message);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing FriendAddEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(ru.sadykov.socialnetwork.friend.event.FriendAddEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.subscriberId)) {
        this.subscriberId = data().deepCopy(fields()[1].schema(), other.subscriberId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.message)) {
        this.message = data().deepCopy(fields()[2].schema(), other.message);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public long getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public ru.sadykov.socialnetwork.friend.event.FriendAddEvent.Builder setUserId(long value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public ru.sadykov.socialnetwork.friend.event.FriendAddEvent.Builder clearUserId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'subscriberId' field.
      * @return The value.
      */
    public long getSubscriberId() {
      return subscriberId;
    }


    /**
      * Sets the value of the 'subscriberId' field.
      * @param value The value of 'subscriberId'.
      * @return This builder.
      */
    public ru.sadykov.socialnetwork.friend.event.FriendAddEvent.Builder setSubscriberId(long value) {
      validate(fields()[1], value);
      this.subscriberId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'subscriberId' field has been set.
      * @return True if the 'subscriberId' field has been set, false otherwise.
      */
    public boolean hasSubscriberId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'subscriberId' field.
      * @return This builder.
      */
    public ru.sadykov.socialnetwork.friend.event.FriendAddEvent.Builder clearSubscriberId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public ru.sadykov.socialnetwork.friend.event.FriendAddEvent.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.message = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public ru.sadykov.socialnetwork.friend.event.FriendAddEvent.Builder clearMessage() {
      message = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FriendAddEvent build() {
      try {
        FriendAddEvent record = new FriendAddEvent();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.Long) defaultValue(fields()[0]);
        record.subscriberId = fieldSetFlags()[1] ? this.subscriberId : (java.lang.Long) defaultValue(fields()[1]);
        record.message = fieldSetFlags()[2] ? this.message : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FriendAddEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<FriendAddEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FriendAddEvent>
    READER$ = (org.apache.avro.io.DatumReader<FriendAddEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.userId);

    out.writeLong(this.subscriberId);

    out.writeString(this.message);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.userId = in.readLong();

      this.subscriberId = in.readLong();

      this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.userId = in.readLong();
          break;

        case 1:
          this.subscriberId = in.readLong();
          break;

        case 2:
          this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










