name: backend pipeline

on:
  pull_request:
    branches:
      - main
      - realise-1.0.0

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Run Checkstyle
        run: mvn clean verify -DskipTests=true

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests=true

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Run Tests
        run: mvn test

      - name: Calculate Test Coverage
        run: |
          percentage=$(awk -F"," '{ instructions += $4 + $5; covered += $5 } END { if (instructions > 0) print 100 * covered / instructions; else print 0 }' $(find . -name "jacoco.csv"))
          echo "Test Coverage: $percentage%"